#! /usr/bin/env node
'use strict';

var shell = require('child_process').execFile;
shell('grunt', function(error, stderr, stdout) {
    console.log('stderr: ' + stderr);
    console.log('stdout: ' + stdout);
    if (error) {
        console.log('error: ' + error);
        process.exit(1);
    }
});